### PR TITLE
Fix storage of order date

### PR DESCRIPTION
**Pull request by ryenl**

### CODE REVIEW

**Review by calebchongsj — APPROVED** [review]

**Review by calebchongsj — COMMENTED** [review]
Are you sure you aren’t adding a new feature with orderDate?

**Comment by ryenl** [comment]
> Are you sure you aren’t adding a new feature with orderDate?

each order already had a order date field, it was not properly saved into the json file

**Review by calebchongsj — APPROVED** [review]
Looks good to me Ryan! Thanks for saving into the Json file.

**Comment by ryenl** [comment]
> Looks good to me Ryan! Thanks for saving into the Json file.

On second thought you are right Caleb. Feature freeze does not allow updates data files bundle within the app. Thanks for pointing it out!

**Pull request closed without merging**
